services:
  reviews:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: ./backend
          ignore:
            - ./backend/node_modules/
    volumes: 
      - ./backend/logs:/backend/logs

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: ./frontend
          ignore:
            - ./frontend/node_modules/
    environment:
      - API_URL=http://reviews:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
