services:
  reviews:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: ./backend
          ignore:
            - ./backend/node_modules/
    volumes: 
      - ./backend/logs:/backend/logs

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: ./frontend
          ignore:
            - ./frontend/node_modules/
    environment:
      - API_URL=http://reviews:${PORT}
      - NEXT_PUBLIC_API_URL=${API_URL}
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "${DOCKER_PORT}:${DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
